--- #YAML:1.0
name:                HTML-GoogleMaps-V3
version:             10
abstract:            a simple wrapper around the Google Maps API
license:             ~
author:              
    - Lee Johnson <leejo@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Geo::Coder::Google:            0.02
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
